apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: certsecret
data:
  ca.crt: NYOMIO_SAN_CA_BASE64
  tls.crt: NYOMIO_SAN_CERT_BASE64
  tls.key: NYOMIO_SAN_KEY_BASE64
  tls.pkcs8: NYOMIO_SAN_KEY_PKCS8_BASE64
  java_keystore.jks: JAVA_KEYSTORE_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: certsecret
data:
  ca.crt: NYOMIO_SAN_CA_BASE64
  tls.crt: NYOMIO_SAN_CERT_BASE64
  tls.key: NYOMIO_SAN_KEY_BASE64
  tls.pkcs8: NYOMIO_SAN_KEY_PKCS8_BASE64
  java_keystore.jks: JAVA_KEYSTORE_BASE64
