apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: certsecret
data:
  tls.crt: NYOMIO_SAN_CERT_BASE64
  tls.key: NYOMIO_SAN_KEY_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: certsecret
data:
  tls.crt: NYOMIO_SAN_CERT_BASE64
  tls.key: NYOMIO_SAN_KEY_BASE64
