kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutetcps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - tlsoptions
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress
subjects:
  - kind: ServiceAccount
    name: traefik-ingress
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress
  namespace: kube-system
---
{{ if eq .Values.global.clusterType "minikube" }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress
      containers:
        - name: traefik
          image: traefik:2.0.7
          args:
            - --api.insecure
            - --accesslog
            - --log=true
            - --log.level=info
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --entrypoints.postgres.Address=:5432
            - --entrypoints.kafka1.Address=:32400
            - --entrypoints.kafka2.Address=:32401
            - --entrypoints.logstash.Address=:4560
            - --providers.kubernetescrd
            - --providers.kubernetesingress=true
          ports:
            - name: web
              containerPort: 8000
              hostPort: 80
            - name: websecure
              containerPort: 4443
              hostPort: 443
            - name: postgres
              containerPort: 5432
              hostPort: 5432
            - name: kafka1
              containerPort: 32400
              hostPort: 32400
            - name: kafka2
              containerPort: 32401
              hostPort: 32401
            - name: logstash
              containerPort: 4560
              hostPort: 4560
            - name: admin
              containerPort: 8080
              hostPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
---
{{ else }}
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress
      containers:
        - name: traefik
          image: traefik:2.0.7
          args:
            - --api.insecure
            - --accesslog
            - --log=true
            - --log.level=info
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --entrypoints.postgres.Address=:5432
            - --entrypoints.kafka1.Address=:32400
            - --entrypoints.kafka2.Address=:32401
            - --entrypoints.logstash.Address=:4560
            - --providers.kubernetescrd
            - --providers.kubernetesingress=true
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: postgres
              containerPort: 5432
            - name: kafka1
              containerPort: 32400
            - name: kafka2
              containerPort: 32401
            - name: logstash
              containerPort: 4560
            - name: admin
              containerPort: 8080
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: traefik-ingress
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
    - protocol: TCP
      name: https
      port: 443
      targetPort: 4443
    - protocol: TCP
      name: postgres
      port: 5432
      targetPort: 5432
    - protocol: TCP
      name: kafka1
      port: 32400
      targetPort: 32400
    - protocol: TCP
      name: kafka2
      port: 32401
      targetPort: 32401
    - protocol: TCP
      name: logstash
      port: 4560
      targetPort: 4560
  selector:
    app: traefik
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-system
  name: traefik-dashboard
spec:
  selector:
    app: traefik
  ports:
    - port: 8080
      name: admin
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: kube-system
  name: traefik-admin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.nyomio.local`)
      kind: Rule
      priority: 1
      services:
        - name: traefik-dashboard
          port: 8080
  tls:
    secretName: certsecret
