apiVersion: apps/v1
kind: Deployment
metadata:
  name: "auth-deployment"
spec:
  selector:
    matchLabels:
      app: "auth"
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "auth"
    spec:
      containers:
        - name: "auth"
          image: "auth:v1"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: debug
              containerPort: 8000
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nyom-app-oauth-client
                  key: secret
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nyom-apps
                  key: jwtsecret
---
apiVersion: v1
kind: Service
metadata:
  name: "auth-service"
spec:
  selector:
    app: "auth"
  ports:
    - name: http
      targetPort: 8080
      port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: "2"
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
    - host: app.nyomio.local
      http:
        paths:
          - path: /oauth/
            backend:
              serviceName: auth-service
              servicePort: http
          - path: /logout
            backend:
              serviceName: auth-service
              servicePort: http
          - path: /api
            backend:
              serviceName: auth-service
              servicePort: http
