apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: framework-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak
          env:
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-initial-admin
                key: password
          - name: DB_VENDOR
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_ADDR
            value: postgresql.framework-demo.svc.cluster.local
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-user
                key: password
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u keycloak -p $KEYCLOAK_ADMIN_PASSWORD;
                while ! /opt/jboss/keycloak/bin/jboss-cli.sh --connect /:reload; do echo 'wait for keycloak ready'; done;"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: keycloak
  name: keycloak
  namespace: framework-demo
spec:
  ports:
    - port: 80
      targetPort: 80
      name: keycloak-http
    - port: 8443
      targetPort: 8443
      name: keycloak-https
  selector:
    k8s-app: keycloak