apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: sso.nyomio.local
      http:
        paths:
          - path: /
            backend:
              serviceName: nyom-sso-keycloak-http
              servicePort: http
