apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgdata
  namespace: framework-demo
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user
  namespace: framework-demo
type: Opaque
data:
  password: NmVFRXBaZDQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: framework-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: postgres
    spec:
      volumes:
        - name: pv-pgdata
          persistentVolumeClaim:
            claimName: pvc-pgdata
      containers:
        - name: postgres
          image: postgres:alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pv-pgdata
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: postgres
  name: postgresql
  namespace: framework-demo
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-port
  selector:
    k8s-app: postgres