---
micronaut:
  application:
    name: auth
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - "https://app.nyomio.local:4200"
---
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET_KEY}
    endpoints:
      logout:
        enabled: true
    oauth2:
      enabled: true
      clients:
        keycloak:
          client-id: nyom-app
          client-secret: ${CLIENT_SECRET}
          openid:
            issuer: 'https://sso.nyomio.local/auth/realms/nyomio'
