micronaut:
  application:
    name: admin
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  db:
    driver: org.postgresql.Driver
    connection-string: jdbc:postgresql://localhost:3306/nyom
    user: postgres
    password: ${DB_PASSWORD}
