apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-password
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  password: {{ if .Values.global.dev }}{{ b64enc "f2Tt8YXBUJRipRCk" | quote }}{{ else }}{{ randAlphaNum 16 | b64enc | quote }}{{ end }}

