apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      serviceAccountName: secret-writer
      containers:
        - name: keycloak
          image: jboss/keycloak:8.0.1
          env:
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-admin-password
                key: password
          - name: KEYCLOAK_USER
            value: keycloak
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: DB_VENDOR
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_ADDR
            value: postgresql.{{ .Release.Namespace }}.svc.cluster.local
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-user
                key: password
{{ if or (eq .Values.global.clusterType "docker") (eq .Values.global.clusterType "minikube") }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/script/postStart.sh &> /tmp/poststart.log"]
          volumeMounts:
            - name: keycloak-poststart-volume
              mountPath: /script/postStart.sh
              subPath: postStart.sh
      volumes:
        - name: keycloak-poststart-volume
          configMap:
            name: keycloak-poststart
            defaultMode: 0777
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: keycloak
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: keycloak-http
    - port: 8443
      targetPort: 8443
      name: keycloak-https
  selector:
    app: keycloak
