apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webapp-dev-skaffold"
spec:
  selector:
    matchLabels:
      app: "webapp-dev-skaffold"
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "webapp-dev-skaffold"
    spec:

      containers:
        - name: "webapp-dev-skaffold"
          image: "webapp-dev-skaffold"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: "webapp-dev-skaffold-service"
spec:
  selector:
    app: "webapp-dev-skaffold"
  ports:
    - name: http
      targetPort: 4200
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webapp-dev-skaffold-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app.nyomio.local`)
      kind: Rule
      priority: 1
      services:
        - name: webapp-dev-skaffold-service
          port: 80
  tls:
    secretName: certsecret
